### ISSUE TITLE
PC vendor CSS prefix

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/paperclip#107]
This could provide additional functionality that isn't supported by HTML and CSS out of the box. For example:

<img width="267" alt="Screen Shot 2022-10-02 at 4 06 21 PM" src="https://user-images.githubusercontent.com/757408/193476274-7fd8e5c2-39e9-4227-9a36-0305bee82ac5.png">

Can be expressed with:

```css
div {
  style {

    /* left right top bottom */
    --pc-constraints: 10px 10px 10px 10px
  }
}
```

Could be compiled to:

```css
._class {
  left: 10px;
  top: 10px;
  position: absolute;
  width: calc(100% - 10px);
  height: calc(100% - 10px);
}
```

Considerations:

- Ensure taht
